#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# monitor="$(xrandr -q | grep ' connected' | cut -d" " -f1)"

if [[ $(xrandr -q | grep 'HDMI-0 connected') ]]; then
	bspc monitor DP-4 -d I II III IV V
	bspc monitor HDMI-0 -d VI VII VIII IX X
else
	bspc monitor DP-4 -d I II III IV V VI VII VIII IX X
fi
bspc config border_width	2
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# 
# Custom launch
#

# Launch Polybar
~/.config/polybar/./launch.sh

# Fix mouse cursor "x"
xsetroot -cursor_name left_ptr

# Focus on mouse hover
bspc config focus_follows_pointer true

# Disable screen saver
xset -dpms s off

# Colors
bspc config normal_border_color		"#111111"
bspc config focused_border_color	"#7f689a"
bspc config presel_feedback_color	"#7f689a"
