#! /bin/sh

##
# This script configures bspwm
##

##
# Workspaces and resolution
##

if [[ $(xrandr -q | grep "$EXTRA_MONITOR connected") ]]; then
	echo "Config external monitor resolution"

    side="--right-of"

    if [ "$EXTRA_MONITOR_SIDE" == "left" ]; then
        side="--left-of"
    fi

	xrandr --output $MONITOR --auto --scale 1x1 --dpi 110 --primary 
    xrandr --output $EXTRA_MONITOR --dpi 110 --rotate $EXTRA_MONITOR_ROTATION "$side" $MONITOR --scale 1x1 --mode "$EXTRA_MONITOR_RESOLUTION"

	# Set workspaces
    if [ "$EXTRA_MONITOR_SIDE" == "left" ]; then
	    bspc monitor $EXTRA_MONITOR -d 6 7 8 9 10
        bspc monitor $MONITOR -d 1 2 3 4 5
    else
        bspc monitor $MONITOR -d 1 2 3 4 5
	    bspc monitor $EXTRA_MONITOR -d 6 7 8 9 10
    fi
	
else	
    # Config single monitor
    xrandr --output $MONITOR --scale 1x1 --primary --dpi 102 --auto

    if [ ! -z "$CUSTOM_RESOLUTION" ]; then
	    xrandr --output $MONITOR --mode "$CUSTOM_RESOLUTION"
    fi

	# Set workspaces
	bspc monitor $MONITOR -d 1 2 3 4 5 6 7 8 9 10
	
fi

##
# Style
##

bspc config border_width	1
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Colors
bspc config normal_border_color		"#111111"
bspc config focused_border_color	"#7f689a"
bspc config presel_feedback_color	"#7f689a"

##
# Configs
##

# Focus on mouse hover
bspc config focus_follows_pointer true

# Fix mouse cursor "x"
xsetroot -cursor_name left_ptr

# Disable screen saver
xset -dpms s off

## 
# Custom launch
##

# Launch Polybar
bash ~/.config/polybar/launch.sh &

# Autostart apps
# sh ~/.config/bspwm/autostart.sh

# Wallpaper 
feh --bg-fill $WALLPAPER &

# Key binding
pgrep -x sxhkd > /dev/null || sxhkd &

exit 0
