#! /bin/sh

##
# This script configures bspwm
##

pgrep -x sxhkd > /dev/null || sxhkd &

# monitor="$(xrandr -q | grep ' connected' | cut -d" " -f1)"

##
# Workspaces and resolution
##

MONITOR='DP-4'
MONITOR_RIGHT='HDMI-0'

if [[ $(xrandr -q | grep "$MONITOR_RIGHT connected") ]]; then
	# Config external monitor resolution
	xrandr --output $MONITOR --auto --scale 1x1 --dpi 110 --primary --output $MONITOR_RIGHT --dpi 110 --mode 1920x1080 --rotate normal --right-of $MONITOR --scale 1x1

	# Set workspaces
	bspc monitor $MONITOR -d I II III IV V
	bspc monitor $MONITOR_RIGHT -d VI VII VIII IX X
	
else	
	# Config single monitor
	xrandr --output $MONITOR --scale 1x1 --primary --dpi 102

	# Set workspaces
	bspc monitor $MONITOR -d I II III IV V VI VII VIII IX X
	
fi

##
# Style
##

bspc config border_width	1
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Colors
bspc config normal_border_color		"#111111"
bspc config focused_border_color	"#7f689a"
bspc config presel_feedback_color	"#7f689a"

##
# Rules
##

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

##
# Configs
##

# Focus on mouse hover
bspc config focus_follows_pointer true

# Fix mouse cursor "x"
xsetroot -cursor_name left_ptr

# Disable screen saver
xset -dpms s off

## 
# Custom launch
##

# Launch Polybar
~/.config/polybar/./launch.sh

# Autostart apps
# sh ~/.config/bspwm/autostart.sh

# Wallpaper 
feh --bg-fill $WALLPAPER
